In [1]:
import numpy as np

In [4]:
my_list1 = [1,2,3,4]

In [6]:
#Creating array

my_array1 = np.array(my_list1)

In [7]:
my_list2 = [11, 12, 13, 14]

In [8]:
my_lists = [my_list1, my_list2]

In [11]:
# Making multid array

my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [13]:
# Get the shape of the array

my_array2.shape

(2, 4)

In [14]:
my_array2.dtype

dtype('int64')

In [15]:
# Creating array with zeros

my_zeros_array = np.zeros(5)

In [20]:
# Getting the data type of the array

my_zeros_array.dtype

dtype('float64')

In [24]:
# Creating array with ones

np.ones([5, 5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [22]:
# Creating an empty array

np.empty(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [26]:
# Identity matrix it will be sqare matrix

np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
# This method takes three arrguments (start, stop, step)

np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])