In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Sqart root

np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
# exponantial series

np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
# Generating random numbers

A = np.random.randn(10)
A

array([ 0.15568437, -0.36374016,  0.07436272,  0.1979586 , -0.10159996,
        0.21043018, -1.09171785, -0.24233828,  0.3528402 ,  0.1474749 ])

In [9]:
B = np.random.randn(10)
B

array([-0.02629539, -0.27947541,  0.85240106,  1.69721842,  0.24884644,
        2.50086377, -0.56896774, -0.33845815, -0.21966057,  1.46752543])

In [11]:
# Binary Funtions

np.add(A, B)

array([ 0.12938898, -0.64321557,  0.92676379,  1.89517702,  0.14724648,
        2.71129395, -1.66068559, -0.58079643,  0.13317963,  1.61500033])

In [12]:
np.maximum(A, B)

array([ 0.15568437, -0.27947541,  0.85240106,  1.69721842,  0.24884644,
        2.50086377, -0.56896774, -0.24233828,  0.3528402 ,  1.46752543])

In [17]:
url = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations'

# Open URL in a new tab, if a browser window is already open.
webbrowser.open_new_tab(url)

# Open URL in new window, raising the window if possible.
# webbrowser.open_new(url)

True