In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
# Save the single numpy array

np.save('myarr', arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# In order to load numpy array use the extension

np.load('myarr.npy')

array([0, 1, 2, 3, 4])

In [6]:
arr2 = np.load('myarr.npy')

In [7]:
arr3 = np.arange(20)

In [8]:
# Save the multiple numpy array

np.savez('ziparray.npz', x=arr, y=arr2, z=arr3)

In [9]:
archive_array = np.load('ziparray.npz')
archive_array['z']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.savetxt('myarraytext.txt', arr3, delimiter=',')

In [11]:
arr4 = np.loadtxt('myarraytext.txt', delimiter=',')
arr4

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.])